# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies and create package-lock.json if missing
      run: |
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found, running npm install to generate it."
          npm install
        else
          echo "package-lock.json found, proceeding with npm ci."
        fi

    - name: Clean install dependencies using package-lock.json
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

